import { 
  Player, 
  Match, 
  Tournament, 
  Season, 
  RatingConfig, 
  Award, 
  Trophy, 
  NewsArticle, 
  MediaItem, 
  Fixture, 
  AuditLog, 
  ClubMilestone, 
  Permission, 
  Role, 
  User,
  ClubAnnouncement
} from '../src/types';
import { hashPassword } from './authUtils';

export const initialRatingConfig: RatingConfig = {
  id: 'cfg-default-v1',
  version: '1.2.0',
  baseRating: 65,
  winWeight: 10,
  goalWeight: 3.5,
  assistWeight: 2.5,
  cleanSheetWeight: 4.0,
  motmWeight: 5.0,
  opponentStrengthWeight: 0.15,
  tournamentMultiplier: {
    Major: 1.4,
    Championship: 1.25,
    Cup: 1.15,
    Friendly: 1.0,
  },
  formWeight: 2.0,
  updatedAt: '2026-09-01T12:00:00Z',
  updatedBy: 'Chief Statistics Officer (Admin)',
};

export const initialSeasons: Season[] = [
  {
    id: 's01-2026',
    name: 'Season 01 — 2026',
    code: 'S01-2026',
    startDate: '2026-01-10',
    endDate: '2026-12-20',
    isCurrent: true,
    status: 'ONGOING',
    totalMatches: 42,
    wins: 32,
    draws: 6,
    losses: 4,
    winRate: 76.2,
    goalsScored: 114,
    goalsConceded: 38,
    currentClubRank: '1st in National eFootball Pro Circuit',
  },
  {
    id: 's00-2025',
    name: 'Inaugural Cup — 2025',
    code: 'S00-2025',
    startDate: '2025-06-01',
    endDate: '2025-12-15',
    isCurrent: false,
    status: 'COMPLETED',
    totalMatches: 24,
    wins: 18,
    draws: 3,
    losses: 3,
    winRate: 75.0,
    goalsScored: 62,
    goalsConceded: 21,
    currentClubRank: 'Champions',
  },
];

export const initialPlayers: Player[] = [
  {
    id: 'p-noyon',
    slug: 'noyon',
    name: 'Noyon Hossain',
    gamingName: 'NOYON',
    efootballId: 'BDPSC-7789-NOYON',
    jerseyNumber: 10,
    position: 'CF',
    photoUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    joinDate: '2025-06-01',
    bio: 'Lead Striker and Captain of BD Power Strikers Club. Renowned in the South Asian eFootball circuit for lethal finishing, counter-attacking precision, and clutch 90th-minute goals.',
    preferredPlatform: 'Mobile',
    playstyle: 'Goal Poacher / Fast Break',
    favoriteTeam: 'FC Barcelona',
    socialHandle: '@noyon_efootball',
    rating: 94,
    overallRank: 1,
    weeklyRank: 1,
    monthlyRank: 1,
    seasonRank: 1,
    formRank: 1,
    rankMovement: 'UP',
    rankChangeValue: 1,
    totalMatches: 42,
    wins: 33,
    draws: 5,
    losses: 4,
    winRate: 78.5,
    goals: 54,
    assists: 22,
    cleanSheets: 0,
    motmCount: 15,
    form: ['W', 'W', 'W', 'W', 'W'],
    ratingProgression: [
      { date: '2026-07-15', rating: 91, matchId: 'm-01' },
      { date: '2026-08-01', rating: 92, matchId: 'm-03' },
      { date: '2026-08-18', rating: 93, matchId: 'm-05' },
      { date: '2026-09-05', rating: 93, matchId: 'm-07' },
      { date: '2026-09-18', rating: 94, matchId: 'm-09' },
    ],
  },
  {
    id: 'p-ashem',
    slug: 'ashem',
    name: 'Ashraful Ashem',
    gamingName: 'ASHEM_STRIKER',
    efootballId: 'BDPSC-1029-ASHEM',
    jerseyNumber: 7,
    position: 'SS',
    photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    joinDate: '2025-06-01',
    bio: 'Co-founder, tactical anchor, and electric playmaker. Known for unpredictable dribbling in the half-spaces and visionary weighted through-balls.',
    preferredPlatform: 'Mobile',
    playstyle: 'Creative Playmaker / Possession Game',
    favoriteTeam: 'Arsenal',
    socialHandle: '@ashrafulashem',
    rating: 92,
    overallRank: 2,
    weeklyRank: 2,
    monthlyRank: 2,
    seasonRank: 2,
    formRank: 2,
    rankMovement: 'SAME',
    rankChangeValue: 0,
    totalMatches: 40,
    wins: 30,
    draws: 6,
    losses: 4,
    winRate: 75.0,
    goals: 38,
    assists: 34,
    cleanSheets: 0,
    motmCount: 11,
    form: ['W', 'W', 'D', 'W', 'W'],
    ratingProgression: [
      { date: '2026-07-15', rating: 89, matchId: 'm-01' },
      { date: '2026-08-01', rating: 90, matchId: 'm-03' },
      { date: '2026-08-18', rating: 91, matchId: 'm-05' },
      { date: '2026-09-05', rating: 91, matchId: 'm-07' },
      { date: '2026-09-18', rating: 92, matchId: 'm-09' },
    ],
  },
  {
    id: 'p-tanvir',
    slug: 'tanvir',
    name: 'Tanvir Ahmed',
    gamingName: 'TANVIR_MAESTRO',
    efootballId: 'BDPSC-3301-TANVIR',
    jerseyNumber: 8,
    position: 'AMF',
    photoUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    joinDate: '2025-08-15',
    bio: 'Midfield maestro with pinpoint dead-ball accuracy and exceptional stamina. Dictates tempo and switches play with millimeter precision.',
    preferredPlatform: 'Console',
    playstyle: 'Hole Player / Quick Counter',
    favoriteTeam: 'Real Madrid',
    socialHandle: '@tanvir_maestro',
    rating: 89,
    overallRank: 3,
    weeklyRank: 3,
    monthlyRank: 3,
    seasonRank: 3,
    formRank: 4,
    rankMovement: 'DOWN',
    rankChangeValue: 1,
    totalMatches: 36,
    wins: 27,
    draws: 5,
    losses: 4,
    winRate: 75.0,
    goals: 24,
    assists: 29,
    cleanSheets: 0,
    motmCount: 8,
    form: ['W', 'D', 'W', 'L', 'W'],
    ratingProgression: [
      { date: '2026-07-15', rating: 87, matchId: 'm-01' },
      { date: '2026-08-01', rating: 88, matchId: 'm-03' },
      { date: '2026-08-18', rating: 89, matchId: 'm-05' },
      { date: '2026-09-05', rating: 90, matchId: 'm-07' },
      { date: '2026-09-18', rating: 89, matchId: 'm-09' },
    ],
  },
  {
    id: 'p-rakib',
    slug: 'rakib',
    name: 'Rakibul Islam',
    gamingName: 'RAKIB_WALL',
    efootballId: 'BDPSC-4402-RAKIB',
    jerseyNumber: 4,
    position: 'CB',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    joinDate: '2025-09-01',
    bio: 'The defensive fortress of BDPSC. Impeccable shoulder charges, anticipation of through-passes, and unmatched aerial clearance.',
    preferredPlatform: 'Mobile',
    playstyle: 'Build Up / Aggressive Interception',
    favoriteTeam: 'Liverpool',
    socialHandle: '@rakib_thewall',
    rating: 88,
    overallRank: 4,
    weeklyRank: 4,
    monthlyRank: 4,
    seasonRank: 4,
    formRank: 3,
    rankMovement: 'UP',
    rankChangeValue: 2,
    totalMatches: 38,
    wins: 28,
    draws: 6,
    losses: 4,
    winRate: 73.7,
    goals: 6,
    assists: 8,
    cleanSheets: 19,
    motmCount: 5,
    form: ['W', 'W', 'W', 'D', 'W'],
    ratingProgression: [
      { date: '2026-07-15', rating: 85, matchId: 'm-01' },
      { date: '2026-08-01', rating: 86, matchId: 'm-03' },
      { date: '2026-08-18', rating: 87, matchId: 'm-05' },
      { date: '2026-09-05', rating: 87, matchId: 'm-07' },
      { date: '2026-09-18', rating: 88, matchId: 'm-09' },
    ],
  },
  {
    id: 'p-fahim',
    slug: 'fahim',
    name: 'Fahim Shahriar',
    gamingName: 'FAHIM_SPEED',
    efootballId: 'BDPSC-5511-FAHIM',
    jerseyNumber: 11,
    position: 'RWF',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    joinDate: '2025-10-10',
    bio: 'Pacey right winger celebrated for double-touch bursts and devastating cut-backs. Can stretch any stubborn 5-back defensive setup.',
    preferredPlatform: 'Mobile',
    playstyle: 'Roaming Flank / Out Wide',
    favoriteTeam: 'Manchester City',
    socialHandle: '@fahimspeed_bd',
    rating: 86,
    overallRank: 5,
    weeklyRank: 5,
    monthlyRank: 5,
    seasonRank: 5,
    formRank: 5,
    rankMovement: 'SAME',
    rankChangeValue: 0,
    totalMatches: 32,
    wins: 23,
    draws: 5,
    losses: 4,
    winRate: 71.9,
    goals: 19,
    assists: 17,
    cleanSheets: 0,
    motmCount: 4,
    form: ['W', 'W', 'L', 'W', 'D'],
    ratingProgression: [
      { date: '2026-07-15', rating: 83, matchId: 'm-01' },
      { date: '2026-08-01', rating: 84, matchId: 'm-03' },
      { date: '2026-08-18', rating: 85, matchId: 'm-05' },
      { date: '2026-09-05', rating: 85, matchId: 'm-07' },
      { date: '2026-09-18', rating: 86, matchId: 'm-09' },
    ],
  },
  {
    id: 'p-siam',
    slug: 'siam',
    name: 'Siam Chowdhury',
    gamingName: 'SIAM_LOCK',
    efootballId: 'BDPSC-1100-SIAM',
    jerseyNumber: 1,
    position: 'GK',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    joinDate: '2025-07-01',
    bio: 'Number 1 shot-stopper with reflexive manual goalkeeper positioning. Saved 8 decisive penalties in tournament shootouts.',
    preferredPlatform: 'Mobile',
    playstyle: 'Defensive Goalkeeper',
    favoriteTeam: 'Bayern Munich',
    socialHandle: '@siam_gk',
    rating: 85,
    overallRank: 6,
    weeklyRank: 6,
    monthlyRank: 6,
    seasonRank: 6,
    formRank: 6,
    rankMovement: 'UP',
    rankChangeValue: 1,
    totalMatches: 34,
    wins: 25,
    draws: 5,
    losses: 4,
    winRate: 73.5,
    goals: 0,
    assists: 2,
    cleanSheets: 18,
    motmCount: 3,
    form: ['W', 'W', 'D', 'W', 'W'],
    ratingProgression: [
      { date: '2026-07-15', rating: 82, matchId: 'm-01' },
      { date: '2026-08-01', rating: 83, matchId: 'm-03' },
      { date: '2026-08-18', rating: 84, matchId: 'm-05' },
      { date: '2026-09-05', rating: 85, matchId: 'm-07' },
      { date: '2026-09-18', rating: 85, matchId: 'm-09' },
    ],
  },
  {
    id: 'p-mahir',
    slug: 'mahir',
    name: 'Mahir Faisal',
    gamingName: 'MAHIR_TURBO',
    efootballId: 'BDPSC-7712-MAHIR',
    jerseyNumber: 17,
    position: 'LWF',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    status: 'RESERVE',
    joinDate: '2026-02-01',
    bio: 'High-energy super-sub on the left flank. Known for curlers into the top corner when coming off the bench.',
    preferredPlatform: 'Mobile',
    playstyle: 'Prolific Winger',
    favoriteTeam: 'Paris Saint-Germain',
    socialHandle: '@mahir_turbo',
    rating: 81,
    overallRank: 7,
    weeklyRank: 7,
    monthlyRank: 7,
    seasonRank: 7,
    formRank: 7,
    rankMovement: 'NEW',
    rankChangeValue: 0,
    totalMatches: 14,
    wins: 9,
    draws: 3,
    losses: 2,
    winRate: 64.3,
    goals: 8,
    assists: 5,
    cleanSheets: 0,
    motmCount: 1,
    form: ['W', 'D', 'W', 'W', 'L'],
    ratingProgression: [
      { date: '2026-08-01', rating: 78, matchId: 'm-03' },
      { date: '2026-08-18', rating: 80, matchId: 'm-05' },
      { date: '2026-09-18', rating: 81, matchId: 'm-09' },
    ],
  },
  {
    id: 'p-shakil',
    slug: 'shakil',
    name: 'Shakil Anwar',
    gamingName: 'SHAKIL_SHIELD',
    efootballId: 'BDPSC-6609-SHAKIL',
    jerseyNumber: 6,
    position: 'DMF',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
    status: 'RESERVE',
    joinDate: '2026-03-15',
    bio: 'Disciplined destroyer shielding the back four. Shuts down opponent counters before they reach the danger box.',
    preferredPlatform: 'Console',
    playstyle: 'The Destroyer / High Press',
    favoriteTeam: 'Chelsea',
    socialHandle: '@shakil_shield',
    rating: 80,
    overallRank: 8,
    weeklyRank: 8,
    monthlyRank: 8,
    seasonRank: 8,
    formRank: 8,
    rankMovement: 'SAME',
    rankChangeValue: 0,
    totalMatches: 16,
    wins: 11,
    draws: 2,
    losses: 3,
    winRate: 68.8,
    goals: 2,
    assists: 7,
    cleanSheets: 6,
    motmCount: 1,
    form: ['W', 'L', 'W', 'D', 'W'],
    ratingProgression: [
      { date: '2026-08-01', rating: 79, matchId: 'm-03' },
      { date: '2026-09-18', rating: 80, matchId: 'm-09' },
    ],
  },
];

export const initialTournaments: Tournament[] = [
  {
    id: 't-bdec-2026',
    slug: 'bangladesh-efootball-championship-2026',
    name: 'Bangladesh eFootball Championship 2026',
    organizer: 'National Esports Federation Bangladesh (NESFB)',
    seasonId: 's01-2026',
    startDate: '2026-08-10',
    endDate: '2026-09-15',
    format: 'KNOCKOUT',
    status: 'COMPLETED',
    tier: 'Major',
    participantsCount: 16,
    prizePool: '150,000 BDT',
    championTeam: 'BD Power Strikers Club',
    runnerUpTeam: 'Dhaka Dragons eSports',
    clubFinalPosition: 'CHAMPIONS (Gold Medal)',
    topScorer: { name: 'NOYON (BDPSC)', goals: 14 },
    topPerformer: { name: 'ASHEM_STRIKER (BDPSC)', rating: 9.4 },
    description: 'The premier national eFootball tournament bringing together the top 16 elite gaming organizations across Bangladesh.',
    bracket: [
      {
        id: 'bk-qf-1',
        round: 'Quarter Final',
        matchNumber: 1,
        team1: { name: 'BD Power Strikers', score: 4, isClub: true },
        team2: { name: 'Chittagong Titans', score: 1, isClub: false },
        winner: 'BD Power Strikers',
        date: '2026-08-25',
        status: 'COMPLETED',
      },
      {
        id: 'bk-qf-2',
        round: 'Quarter Final',
        matchNumber: 2,
        team1: { name: 'Sylhet Stunners', score: 2, isClub: false },
        team2: { name: 'Rajshahi Royals eSports', score: 3, isClub: false },
        winner: 'Rajshahi Royals eSports',
        date: '2026-08-25',
        status: 'COMPLETED',
      },
      {
        id: 'bk-qf-3',
        round: 'Quarter Final',
        matchNumber: 3,
        team1: { name: 'Dhaka Dragons eSports', score: 5, isClub: false },
        team2: { name: 'Barisal Blasters', score: 2, isClub: false },
        winner: 'Dhaka Dragons eSports',
        date: '2026-08-26',
        status: 'COMPLETED',
      },
      {
        id: 'bk-qf-4',
        round: 'Quarter Final',
        matchNumber: 4,
        team1: { name: 'Khulna Kings Club', score: 3, isClub: false },
        team2: { name: 'Comilla Cyber Strikers', score: 1, isClub: false },
        winner: 'Khulna Kings Club',
        date: '2026-08-26',
        status: 'COMPLETED',
      },
      {
        id: 'bk-sf-1',
        round: 'Semi Final',
        matchNumber: 5,
        team1: { name: 'BD Power Strikers', score: 3, isClub: true },
        team2: { name: 'Rajshahi Royals eSports', score: 0, isClub: false },
        winner: 'BD Power Strikers',
        date: '2026-09-05',
        status: 'COMPLETED',
      },
      {
        id: 'bk-sf-2',
        round: 'Semi Final',
        matchNumber: 6,
        team1: { name: 'Dhaka Dragons eSports', score: 4, isClub: false },
        team2: { name: 'Khulna Kings Club', score: 2, isClub: false },
        winner: 'Dhaka Dragons eSports',
        date: '2026-09-05',
        status: 'COMPLETED',
      },
      {
        id: 'bk-fn-1',
        round: 'Final',
        matchNumber: 7,
        team1: { name: 'BD Power Strikers', score: 4, isClub: true },
        team2: { name: 'Dhaka Dragons eSports', score: 2, isClub: false },
        winner: 'BD Power Strikers',
        date: '2026-09-15',
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 't-asia-cup-2026',
    slug: 'south-asia-esports-clash-2026',
    name: 'South Asia eFootball Masters 2026',
    organizer: 'South Asia Gaming Circuit',
    seasonId: 's01-2026',
    startDate: '2026-09-25',
    endDate: '2026-10-30',
    format: 'GROUP_KNOCKOUT',
    status: 'ONGOING',
    tier: 'Major',
    participantsCount: 24,
    prizePool: '500,000 BDT',
    standings: [
      { position: 1, teamName: 'BD Power Strikers Club', isClub: true, played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 10, goalsAgainst: 2, goalDifference: 8, points: 9 },
      { position: 2, teamName: 'Bengal Warriors (IND)', isClub: false, played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 7, goalsAgainst: 4, goalDifference: 3, points: 6 },
      { position: 3, teamName: 'Karachi Kickers (PAK)', isClub: false, played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 5, goalsAgainst: 8, goalDifference: -3, points: 3 },
      { position: 4, teamName: 'Colombo Strikers (SL)', isClub: false, played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 1, goalsAgainst: 9, goalDifference: -8, points: 0 },
    ],
    description: 'International regional showpiece bringing the top squads from Bangladesh, India, Pakistan, and Sri Lanka.',
  },
  {
    id: 't-super-cup-2026',
    slug: 'bdpsc-summer-invitational-cup-2026',
    name: 'BDPSC Summer Invitational Cup 2026',
    organizer: 'BD Power Strikers Club',
    seasonId: 's01-2026',
    startDate: '2026-06-01',
    endDate: '2026-06-25',
    format: 'KNOCKOUT',
    status: 'COMPLETED',
    tier: 'Cup',
    participantsCount: 8,
    prizePool: '50,000 BDT',
    championTeam: 'BD Power Strikers Club',
    runnerUpTeam: 'Sylhet Stunners',
    clubFinalPosition: 'CHAMPIONS',
    topScorer: { name: 'NOYON (BDPSC)', goals: 8 },
    topPerformer: { name: 'TANVIR_MAESTRO (BDPSC)', rating: 9.1 },
  },
];

export const initialMatches: Match[] = [
  {
    id: 'm-grand-final-2026',
    slug: 'bdpsc-vs-dhaka-dragons-grand-final-2026',
    tournamentId: 't-bdec-2026',
    tournamentName: 'Bangladesh eFootball Championship 2026',
    seasonId: 's01-2026',
    date: '2026-09-15',
    time: '20:00',
    opponentClub: 'Dhaka Dragons eSports',
    opponentLogo: '/opponent-logos/dhaka-dragons.svg',
    opponentStrength: 92,
    homeAway: 'NEUTRAL',
    scoreClub: 4,
    scoreOpponent: 2,
    halfTimeScore: '2 - 1',
    result: 'WIN',
    motmPlayerId: 'p-noyon',
    motmPlayerName: 'NOYON',
    matchScreenshot: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800',
    matchVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    matchReport: 'A breathtaking performance in the Grand Final of BDEC 2026. Captain Noyon netted a hat-trick while Ashraful Ashem orchestrated the midfield with two pinpoint assists and a stunning chip goal in the 88th minute to seal the championship trophy for BD Power Strikers Club.',
    isPublished: true,
    createdAt: '2026-09-15T22:30:00Z',
    playerStats: [
      {
        id: 'ps-m1-noyon',
        matchId: 'm-grand-final-2026',
        playerId: 'p-noyon',
        goals: 3,
        assists: 1,
        cleanSheet: false,
        saves: 0,
        conceded: 2,
        motm: true,
        minutesPlayed: 90,
        performanceScore: 9.8,
        notes: 'Match-winning hat-trick including a curling outside-the-box strike.',
      },
      {
        id: 'ps-m1-ashem',
        matchId: 'm-grand-final-2026',
        playerId: 'p-ashem',
        goals: 1,
        assists: 2,
        cleanSheet: false,
        saves: 0,
        conceded: 2,
        motm: false,
        minutesPlayed: 90,
        performanceScore: 9.3,
        notes: 'Clinical passing vision, won 7 dribble take-ons.',
      },
      {
        id: 'ps-m1-tanvir',
        matchId: 'm-grand-final-2026',
        playerId: 'p-tanvir',
        goals: 0,
        assists: 1,
        cleanSheet: false,
        saves: 0,
        conceded: 2,
        motm: false,
        minutesPlayed: 90,
        performanceScore: 8.4,
      },
      {
        id: 'ps-m1-rakib',
        matchId: 'm-grand-final-2026',
        playerId: 'p-rakib',
        goals: 0,
        assists: 0,
        cleanSheet: false,
        saves: 0,
        conceded: 2,
        motm: false,
        minutesPlayed: 90,
        performanceScore: 8.2,
      },
      {
        id: 'ps-m1-siam',
        matchId: 'm-grand-final-2026',
        playerId: 'p-siam',
        goals: 0,
        assists: 0,
        cleanSheet: false,
        saves: 6,
        conceded: 2,
        motm: false,
        minutesPlayed: 90,
        performanceScore: 8.5,
      },
    ],
  },
  {
    id: 'm-semi-final-2026',
    slug: 'bdpsc-vs-rajshahi-royals-semi-final-2026',
    tournamentId: 't-bdec-2026',
    tournamentName: 'Bangladesh eFootball Championship 2026',
    seasonId: 's01-2026',
    date: '2026-09-05',
    time: '19:00',
    opponentClub: 'Rajshahi Royals eSports',
    opponentLogo: '/opponent-logos/rajshahi-royals.svg',
    opponentStrength: 85,
    homeAway: 'NEUTRAL',
    scoreClub: 3,
    scoreOpponent: 0,
    halfTimeScore: '1 - 0',
    result: 'WIN',
    motmPlayerId: 'p-ashem',
    motmPlayerName: 'ASHEM_STRIKER',
    matchScreenshot: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800',
    matchReport: 'Dominant 3-0 clean sheet in the semi-finals. Rakibul Islam and Siam Chowdhury shut down all attempts, while Ashem scored twice and assisted Noyon for the opener.',
    isPublished: true,
    createdAt: '2026-09-05T21:00:00Z',
    playerStats: [
      {
        id: 'ps-m2-ashem',
        matchId: 'm-semi-final-2026',
        playerId: 'p-ashem',
        goals: 2,
        assists: 1,
        cleanSheet: true,
        saves: 0,
        conceded: 0,
        motm: true,
        minutesPlayed: 90,
        performanceScore: 9.6,
      },
      {
        id: 'ps-m2-noyon',
        matchId: 'm-semi-final-2026',
        playerId: 'p-noyon',
        goals: 1,
        assists: 1,
        cleanSheet: true,
        saves: 0,
        conceded: 0,
        motm: false,
        minutesPlayed: 90,
        performanceScore: 8.9,
      },
      {
        id: 'ps-m2-rakib',
        matchId: 'm-semi-final-2026',
        playerId: 'p-rakib',
        goals: 0,
        assists: 0,
        cleanSheet: true,
        saves: 0,
        conceded: 0,
        motm: false,
        minutesPlayed: 90,
        performanceScore: 9.1,
      },
      {
        id: 'ps-m2-siam',
        matchId: 'm-semi-final-2026',
        playerId: 'p-siam',
        goals: 0,
        assists: 0,
        cleanSheet: true,
        saves: 5,
        conceded: 0,
        motm: false,
        minutesPlayed: 90,
        performanceScore: 9.0,
      },
    ],
  },
  {
    id: 'm-group-asia-1',
    slug: 'bdpsc-vs-bengal-warriors-asia-clash',
    tournamentId: 't-asia-cup-2026',
    tournamentName: 'South Asia eFootball Masters 2026',
    seasonId: 's01-2026',
    date: '2026-09-18',
    time: '21:30',
    opponentClub: 'Bengal Warriors (IND)',
    opponentLogo: '/opponent-logos/bengal-warriors.svg',
    opponentStrength: 88,
    homeAway: 'HOME',
    scoreClub: 3,
    scoreOpponent: 1,
    halfTimeScore: '2 - 0',
    result: 'WIN',
    motmPlayerId: 'p-tanvir',
    motmPlayerName: 'TANVIR_MAESTRO',
    matchScreenshot: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800',
    matchReport: 'Tanvir Ahmed turned on the masterclass with two free-kick goals and set up Fahim Shahriar on the counter. A massive 3-1 victory to top Group A.',
    isPublished: true,
    createdAt: '2026-09-18T23:00:00Z',
    playerStats: [
      {
        id: 'ps-m3-tanvir',
        matchId: 'm-group-asia-1',
        playerId: 'p-tanvir',
        goals: 2,
        assists: 1,
        cleanSheet: false,
        saves: 0,
        conceded: 1,
        motm: true,
        minutesPlayed: 90,
        performanceScore: 9.4,
      },
      {
        id: 'ps-m3-fahim',
        matchId: 'm-group-asia-1',
        playerId: 'p-fahim',
        goals: 1,
        assists: 1,
        cleanSheet: false,
        saves: 0,
        conceded: 1,
        motm: false,
        minutesPlayed: 75,
        performanceScore: 8.7,
      },
      {
        id: 'ps-m3-noyon',
        matchId: 'm-group-asia-1',
        playerId: 'p-noyon',
        goals: 0,
        assists: 1,
        cleanSheet: false,
        saves: 0,
        conceded: 1,
        motm: false,
        minutesPlayed: 90,
        performanceScore: 8.2,
      },
    ],
  },
];

export const initialAwards: Award[] = [
  {
    id: 'aw-potm-sep-2026',
    title: 'Player of the Month — September 2026',
    category: 'POTM',
    playerId: 'p-noyon',
    playerName: 'Noyon Hossain',
    gamingName: 'NOYON',
    playerPhotoUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=400',
    period: 'September 2026',
    seasonId: 's01-2026',
    tournamentId: 't-bdec-2026',
    statsSummary: '11 Goals, 5 Assists, 3 MOTM Awards (4 Wins in 4 Matches)',
    ratingSnapshot: 94,
    awardDate: '2026-09-20',
    description: 'Awarded for an extraordinary knockout stage display that led BDPSC to the Bangladesh eFootball Championship 2026 crown.',
    badgeType: 'DIAMOND',
  },
  {
    id: 'aw-potw-wk38',
    title: 'Player of the Week — Week 38',
    category: 'POTW',
    playerId: 'p-ashem',
    playerName: 'Ashraful Ashem',
    gamingName: 'ASHEM_STRIKER',
    playerPhotoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=400',
    period: 'Week 38 (Sep 14 - Sep 20)',
    seasonId: 's01-2026',
    tournamentId: 't-bdec-2026',
    statsSummary: '3 Goals, 3 Assists, 1 MOTM (Rating: 9.45)',
    ratingSnapshot: 92,
    awardDate: '2026-09-17',
    description: 'Immense match-winning contributions in both the BDEC Semi-Final and Grand Final clashes.',
    badgeType: 'PLATINUM',
  },
  {
    id: 'aw-golden-boot-2026',
    title: 'Golden Boot Winner — BDEC 2026',
    category: 'GOLDEN_BOOT',
    playerId: 'p-noyon',
    playerName: 'Noyon Hossain',
    gamingName: 'NOYON',
    playerPhotoUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=400',
    period: 'Season 01 — BDEC 2026',
    seasonId: 's01-2026',
    tournamentId: 't-bdec-2026',
    statsSummary: '14 Tournament Goals in 7 Matches (2.0 Goals/Game)',
    ratingSnapshot: 94,
    awardDate: '2026-09-15',
    description: 'Top goalscorer of the tournament, netting in every single round from group stage to the final.',
    badgeType: 'GOLD',
  },
  {
    id: 'aw-best-def-2026',
    title: 'Best Defender & Wall Award',
    category: 'BEST_DEFENDER',
    playerId: 'p-rakib',
    playerName: 'Rakibul Islam',
    gamingName: 'RAKIB_WALL',
    playerPhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    period: 'Summer 2026',
    seasonId: 's01-2026',
    statsSummary: '19 Clean Sheets, 88% Tackle Success Rate',
    ratingSnapshot: 88,
    awardDate: '2026-09-01',
    description: 'Recognized by the national eFootball committee as the most impenetrable defender of Season 01.',
    badgeType: 'GOLD',
  },
];

export const initialTrophies: Trophy[] = [
  {
    id: 'tr-bdec-2026',
    tournamentName: 'Bangladesh eFootball Championship 2026',
    year: 2026,
    seasonId: 's01-2026',
    category: 'CHAMPIONS',
    position: 'Champions',
    mvpPlayerName: 'Noyon (BD_Noyon)',
    topScorerName: 'Noyon (14 Goals)',
    participatingPlayerIds: ['p-noyon', 'p-ashem', 'p-tanvir', 'p-rakib', 'p-siam', 'p-fahim'],
    squadMembers: ['Noyon (C)', 'Ashraful Ashem', 'Tanvir Ahmed', 'Rakib Hossain', 'Siam Islam', 'Fahim'],
    trophyImageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&q=80&w=600',
    achievementDescription: 'Champions of Bangladesh after defeating Dhaka Dragons eSports 4-2 in the Grand Final at Bashundhara City Convention Arena.',
    dateAwarded: '2026-09-15',
  },
  {
    id: 'tr-summer-cup-2026',
    tournamentName: 'BDPSC Summer Invitational Cup 2026',
    year: 2026,
    seasonId: 's01-2026',
    category: 'CHAMPIONS',
    position: 'Champions',
    mvpPlayerName: 'Tanvir Ahmed',
    topScorerName: 'Ashraful Ashem (7 Goals)',
    participatingPlayerIds: ['p-noyon', 'p-ashem', 'p-tanvir', 'p-rakib', 'p-mahir'],
    squadMembers: ['Noyon', 'Ashraful Ashem', 'Tanvir Ahmed', 'Rakib Hossain', 'Mahir'],
    trophyImageUrl: 'https://images.unsplash.com/photo-1589487391730-58f20eb2c308?auto=format&fit=crop&q=80&w=600',
    achievementDescription: 'Undefeated run with 5 straight wins in the inaugural invitational club tournament.',
    dateAwarded: '2026-06-25',
  },
  {
    id: 'tr-inaugural-2025',
    tournamentName: 'National Esports Pro Circuit Winter 2025',
    year: 2025,
    seasonId: 's00-2025',
    category: 'CHAMPIONS',
    position: 'Champions',
    mvpPlayerName: 'Ashraful Ashem',
    topScorerName: 'Noyon (9 Goals)',
    participatingPlayerIds: ['p-noyon', 'p-ashem', 'p-tanvir'],
    squadMembers: ['Noyon', 'Ashraful Ashem', 'Tanvir Ahmed'],
    trophyImageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&q=80&w=600',
    achievementDescription: 'First major championship title secured in BDPSC history.',
    dateAwarded: '2025-12-15',
  },
];

export const initialNews: NewsArticle[] = [
  {
    id: 'n-01',
    title: 'BD Power Strikers Crowned National Champions of Bangladesh eFootball 2026!',
    slug: 'bdpsc-crowned-national-champions-bdec-2026',
    coverImageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=1000',
    excerpt: 'In a thrilling 4-2 climax against Dhaka Dragons eSports, BDPSC made history by lifting the prestigious National Championship trophy.',
    content: `In front of thousands of live stream viewers, BD Power Strikers Club delivered a masterclass in counter-attacking football to win the Bangladesh eFootball Championship 2026.

Captain Noyon scored three sensational goals, cementing his position as the nation's premier eFootball goalscorer with the Golden Boot award (14 tournament goals). Co-founder and playmaker Ashraful Ashem was instrumental in unlocking the Dragons' rigid defense with two world-class assists before securing the fourth goal in the dying minutes.

"This trophy belongs to every supporter and member of BDPSC who believed in our tactical discipline," said Noyon during the trophy ceremony. "We set a benchmark today, but our sights are now locked on the South Asia eFootball Masters."`,
    author: 'BDPSC Media Team',
    publishedAt: '2026-09-16T10:00:00Z',
    category: 'TOURNAMENT',
    tags: ['Champions', 'BDEC2026', 'Trophy', 'Noyon', 'Ashem'],
    relatedPlayerIds: ['p-noyon', 'p-ashem'],
    relatedTournamentId: 't-bdec-2026',
    status: 'PUBLISHED',
  },
  {
    id: 'n-02',
    title: 'Official Rating Engine Update v1.2 Released with Form Factor Calibration',
    slug: 'official-rating-engine-update-v1-2-released',
    coverImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=1000',
    excerpt: 'The BDPSC competitive analytics department has refined the Power Rating algorithm to accurately reward defensive contributions and clean sheets.',
    content: `BD Power Strikers Club has officially deployed Version 1.2 of its proprietary Rating & Ranking Engine. 

The update incorporates enhanced weighting for clean sheets, defensive clearances by defenders and goalkeepers, and adjusts the tournament tier multiplier for international matches. All rankings and historical snapshots have been transparently synchronized across the public portal.`,
    author: 'Chief Statistics Officer',
    publishedAt: '2026-09-10T14:30:00Z',
    category: 'ANNOUNCEMENT',
    tags: ['RatingEngine', 'Analytics', 'Rankings', 'Algorithm'],
    relatedPlayerIds: ['p-rakib', 'p-siam'],
    status: 'PUBLISHED',
  },
  {
    id: 'n-03',
    title: 'BDPSC Roars in South Asia Masters with 3-1 Triumph over Bengal Warriors',
    slug: 'bdpsc-triumphs-over-bengal-warriors-south-asia-masters',
    coverImageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=1000',
    excerpt: 'Tanvir Ahmed scores two breathtaking direct free-kicks as BD Power Strikers claim top spot in Group A of the international circuit.',
    content: `Opening their international campaign in style, BDPSC defeated Indian powerhouse Bengal Warriors 3-1. Tanvir Ahmed received Man of the Match honors after executing two unstoppable curling set-pieces from 28 yards.`,
    author: 'Esports Correspondent',
    publishedAt: '2026-09-19T08:00:00Z',
    category: 'MATCH_REPORT',
    tags: ['SouthAsiaMasters', 'Tanvir', 'MatchReport', 'Victory'],
    relatedPlayerIds: ['p-tanvir', 'p-fahim'],
    relatedTournamentId: 't-asia-cup-2026',
    status: 'PUBLISHED',
  },
];

export const initialMedia: MediaItem[] = [
  {
    id: 'med-01',
    title: 'Grand Final Victory Moment — Lifting the BDEC 2026 Cup',
    category: 'PHOTOS',
    mediaUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=1200',
    uploadedAt: '2026-09-16T12:00:00Z',
    tags: ['Champions', 'Trophy', 'Team', 'BDEC2026'],
    description: 'BD Power Strikers roster celebrating the national championship victory.',
  },
  {
    id: 'med-02',
    title: 'Official Digital Player Card — Noyon (OVR 94 Signature Edition)',
    category: 'CARDS',
    mediaUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=800',
    uploadedAt: '2026-09-18T15:00:00Z',
    tags: ['PlayerCard', 'Noyon', 'OVR94', 'Striker'],
    description: 'Signature gold card generated for Captain Noyon.',
  },
  {
    id: 'med-03',
    title: 'Match Screenshot: 90th Minute Climax vs Dhaka Dragons',
    category: 'SCREENSHOTS',
    mediaUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=1200',
    uploadedAt: '2026-09-15T23:10:00Z',
    tags: ['MatchScreenshot', 'FinalScore', 'eFootballMobile'],
    description: 'Scoreboard verification screenshot showing 4-2 full-time result.',
  },
  {
    id: 'med-04',
    title: 'Highlights: BDEC 2026 Grand Final Full Extended Highlights',
    category: 'VIDEOS',
    mediaUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1200',
    externalVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    uploadedAt: '2026-09-17T09:30:00Z',
    tags: ['Highlights', 'YouTube', 'GrandFinal', 'Gameplay'],
    description: 'All 6 goals from the sensational grand final showdown.',
  },
];

export const initialFixtures: Fixture[] = [
  {
    id: 'fix-01',
    date: '2026-09-28',
    time: '21:00',
    homeTeam: 'BD Power Strikers',
    homeTeamLogo: '/logo.svg',
    opponent: 'Karachi Kickers (PAK)',
    opponentLogo: '/opponent-logos/karachi-kickers.svg',
    tournament: 'South Asia eFootball Masters 2026',
    tournamentId: 't-asia-cup-2026',
    lineupPlayerIds: ['p-noyon', 'p-ashem', 'p-tanvir', 'p-rakib', 'p-siam'],
    status: 'SCHEDULED',
    venuePlatform: 'eFootball Official Online Room (Server Asia-01)',
  },
  {
    id: 'fix-02',
    date: '2026-10-05',
    time: '20:30',
    homeTeam: 'BD Power Strikers',
    homeTeamLogo: '/logo.svg',
    opponent: 'Colombo Strikers (SL)',
    opponentLogo: '/opponent-logos/colombo-strikers.svg',
    tournament: 'South Asia eFootball Masters 2026',
    tournamentId: 't-asia-cup-2026',
    lineupPlayerIds: ['p-noyon', 'p-ashem', 'p-fahim', 'p-rakib', 'p-siam'],
    status: 'SCHEDULED',
    venuePlatform: 'eFootball Cross-Play Arena',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-01',
    timestamp: '2026-09-15T22:45:00Z',
    actor: 'admin@bdpsc.club (Super Admin)',
    action: 'CREATE_MATCH_RECORD',
    entityType: 'MATCH',
    entityId: 'm-grand-final-2026',
    newValue: { score: '4-2', opponent: 'Dhaka Dragons eSports', tournament: 'BDEC 2026' },
    reason: 'Official Grand Final scoreline and player performances entered.',
  },
  {
    id: 'log-02',
    timestamp: '2026-09-15T22:46:00Z',
    actor: 'SYSTEM_AUTOMATION (Rating Engine)',
    action: 'RECALCULATE_RATINGS_AND_RANKINGS',
    entityType: 'RANKINGS',
    entityId: 'all-players',
    reason: 'Automatic trigger: Match m-grand-final-2026 recorded. Noyon promoted to OVR 94 (#1 Rank).',
  },
  {
    id: 'log-03',
    timestamp: '2026-09-16T11:00:00Z',
    actor: 'admin@bdpsc.club (Super Admin)',
    action: 'CREATE_AWARD',
    entityType: 'AWARD',
    entityId: 'aw-potm-sep-2026',
    newValue: { winner: 'Noyon Hossain', category: 'POTM' },
    reason: 'Player of the Month September 2026 published following national championship.',
  },
];

export const initialMilestones: ClubMilestone[] = [
  {
    id: 'mile-01',
    date: '2024-03-15',
    title: 'Club Foundation & First Squad Assembly',
    category: 'FOUNDATION',
    description: 'BD Power Strikers Club (BDPSC) was established by Ashraful Ashem and Noyon Hossain with an initial roster of elite competitive mobile eFootball athletes.',
  },
  {
    id: 'mile-02',
    date: '2024-11-20',
    title: 'First National Invitational Championship',
    category: 'CHAMPIONSHIP',
    description: 'BDPSC clinched its maiden national trophy in the Dhaka Premier eFootball Invitational without dropping a single match in group or knockout stages.',
  },
  {
    id: 'mile-03',
    date: '2025-08-14',
    title: '50th Competitive Match Milestone',
    category: 'RECORDS',
    description: 'Club reached 50 competitive fixtures with an astounding 78% win rate and 150+ total competitive goals scored.',
  },
  {
    id: 'mile-04',
    date: '2026-09-15',
    title: 'BDEC National Grand Champions 2026',
    category: 'MAJOR_TROPHY',
    description: 'Crowned undisputed Bangladesh eFootball Champions 2026 with a thrilling 4-2 comeback victory over Dhaka Dragons Esports.',
  },
];

export const initialPermissions: Permission[] = [
  // Players
  { id: 'players.view', name: 'View Players', category: 'PLAYERS', description: 'View full player roster, metrics, and profiles.' },
  { id: 'players.create', name: 'Create Players', category: 'PLAYERS', description: 'Register new athlete profiles into BDPSC.' },
  { id: 'players.edit', name: 'Edit Players', category: 'PLAYERS', description: 'Modify player information, positions, jersey, and status.' },
  { id: 'players.delete', name: 'Delete Players', category: 'PLAYERS', description: 'Remove player profiles from the club directory.' },
  
  // Matches
  { id: 'matches.view', name: 'View Matches', category: 'MATCHES', description: 'Access competitive match logs and statistics.' },
  { id: 'matches.create', name: 'Create Matches', category: 'MATCHES', description: 'Record official match results, opponents, and player performances.' },
  { id: 'matches.edit', name: 'Edit Matches', category: 'MATCHES', description: 'Update existing match scorelines and player stats.' },
  { id: 'matches.delete', name: 'Delete Matches', category: 'MATCHES', description: 'Delete match records and revert recorded performances.' },

  // Tournaments
  { id: 'tournaments.view', name: 'View Tournaments', category: 'TOURNAMENTS', description: 'View tournament brackets, schedules, and standings.' },
  { id: 'tournaments.create', name: 'Create Tournaments', category: 'TOURNAMENTS', description: 'Create new tournament campaigns and stages.' },
  { id: 'tournaments.edit', name: 'Edit Tournaments', category: 'TOURNAMENTS', description: 'Manage tournament status, fixtures, and prize pools.' },

  // Rankings
  { id: 'rankings.view', name: 'View Rankings', category: 'RANKINGS', description: 'View competitive club leaderboards.' },
  { id: 'rankings.manage', name: 'Manage Rating Formula', category: 'RANKINGS', description: 'Tune rating engine weights and multipliers.' },
  { id: 'rankings.recalculate', name: 'Recalculate Rankings', category: 'RANKINGS', description: 'Execute the statistical recalculation engine.' },

  // News
  { id: 'news.create', name: 'Create News', category: 'NEWS', description: 'Write club news articles and announcements.' },
  { id: 'news.edit', name: 'Edit News', category: 'NEWS', description: 'Update existing articles and editorial copy.' },
  { id: 'news.publish', name: 'Publish News', category: 'NEWS', description: 'Publish or unpublish articles for the public.' },
  { id: 'news.delete', name: 'Delete News', category: 'NEWS', description: 'Remove news articles from the press center.' },

  // Announcements (Moving Ticker)
  { id: 'announcements.view', name: 'View Announcements', category: 'ANNOUNCEMENTS', description: 'View club announcement ticker items.' },
  { id: 'announcements.manage', name: 'Manage Announcements', category: 'ANNOUNCEMENTS', description: 'Create, update, toggle and delete moving marquee announcements.' },

  // Media
  { id: 'media.view', name: 'View Media', category: 'MEDIA', description: 'View the media gallery and assets.' },
  { id: 'media.upload', name: 'Upload Media', category: 'MEDIA', description: 'Upload screenshots, wallpapers, and match highlights.' },
  { id: 'media.edit', name: 'Edit Media', category: 'MEDIA', description: 'Update media captions, tags, and categories.' },
  { id: 'media.delete', name: 'Delete Media', category: 'MEDIA', description: 'Delete media assets from the gallery.' },

  // Users & RBAC
  { id: 'users.view', name: 'View Users', category: 'USERS', description: 'View registered user accounts and link status.' },
  { id: 'users.edit', name: 'Edit Users', category: 'USERS', description: 'Modify user profiles and link to player profiles.' },
  { id: 'users.suspend', name: 'Suspend Users', category: 'USERS', description: 'Suspend or restore access for user accounts.' },
  { id: 'users.delete', name: 'Delete Users', category: 'USERS', description: 'Permanently remove user accounts and sessions.' },
  
  // Roles
  { id: 'roles.view', name: 'View Roles', category: 'ROLES', description: 'View defined club roles and assigned permissions.' },
  { id: 'roles.create', name: 'Create Roles', category: 'ROLES', description: 'Define custom administrative roles.' },
  { id: 'roles.edit', name: 'Edit Roles', category: 'ROLES', description: 'Modify permissions assigned to existing roles.' },
  { id: 'roles.delete', name: 'Delete Roles', category: 'ROLES', description: 'Remove custom roles.' },
  { id: 'permissions.assign', name: 'Assign Permissions', category: 'ROLES', description: 'Assign or revoke roles from users.' },

  // Audit Logs & Settings
  { id: 'audit_logs.view', name: 'View Audit Logs', category: 'AUDIT_LOGS', description: 'View system audit trails and security logs.' },
  { id: 'settings.manage', name: 'Manage Club Settings', category: 'SETTINGS', description: 'Update platform configurations and season policies.' },
];

export const initialRoles: Role[] = [
  {
    id: 'role-super-admin',
    name: 'SUPER_ADMIN',
    displayName: 'Super Administrator',
    description: 'Full unconstrained system authority over all users, roles, matches, rankings, and club records.',
    permissionIds: ['*'],
    isSystem: true,
    color: 'amber',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'role-admin',
    name: 'ADMIN',
    displayName: 'Club Administrator',
    description: 'General administrative operations including players, fixtures, matches, tournaments, news, and media.',
    permissionIds: [
      'users.view', 'users.edit', 'users.suspend', 'users.delete',
      'players.view', 'players.create', 'players.edit',
      'matches.view', 'matches.create', 'matches.edit',
      'tournaments.view', 'tournaments.create', 'tournaments.edit',
      'rankings.view', 'rankings.manage', 'rankings.recalculate',
      'news.create', 'news.edit', 'news.publish',
      'announcements.view', 'announcements.manage',
      'media.view', 'media.upload', 'media.edit',
      'audit_logs.view',
    ],
    isSystem: true,
    color: 'blue',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'role-stats-manager',
    name: 'STATISTICS_MANAGER',
    displayName: 'Statistics Manager',
    description: 'Dedicated authority over matches, player performance statistics, rating calculations, and rankings.',
    permissionIds: [
      'matches.view', 'matches.create', 'matches.edit', 'matches.delete',
      'players.view',
      'rankings.view', 'rankings.manage', 'rankings.recalculate',
      'tournaments.view',
    ],
    isSystem: true,
    color: 'emerald',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'role-editor',
    name: 'EDITOR',
    displayName: 'Content Editor',
    description: 'Management of official news articles, announcements, match reports, and press releases.',
    permissionIds: [
      'news.create', 'news.edit', 'news.publish', 'news.delete',
      'announcements.view', 'announcements.manage',
      'media.view', 'media.upload', 'media.edit',
    ],
    isSystem: true,
    color: 'purple',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'role-media-manager',
    name: 'MEDIA_MANAGER',
    displayName: 'Media Manager',
    description: 'Manages athlete photos, tournament screenshots, video highlights, and digital wallpapers.',
    permissionIds: [
      'media.view', 'media.upload', 'media.edit', 'media.delete',
      'players.view', 'news.view',
    ],
    isSystem: true,
    color: 'rose',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'role-player',
    name: 'PLAYER',
    displayName: 'BDPSC Athlete',
    description: 'Official roster athlete with dedicated private player dashboard, statistics, and digital card.',
    permissionIds: [
      'players.view', 'matches.view', 'tournaments.view', 'rankings.view', 'media.view',
    ],
    isSystem: true,
    color: 'teal',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'role-member',
    name: 'MEMBER',
    displayName: 'Club Member',
    description: 'Registered supporter with personalized account and club community access.',
    permissionIds: [],
    isSystem: true,
    color: 'slate',
    createdAt: '2025-01-01T00:00:00Z',
  },
];

// Pre-hashed passwords for seed accounts (Password123!)
const defaultHashed = hashPassword('Password123!', 'bdpsc-seed-salt-2026');

export const initialUsers: User[] = [
  {
    id: 'usr-ashem',
    email: 'ashrafulashem@gmail.com',
    passwordHash: defaultHashed.hash,
    salt: defaultHashed.salt,
    name: 'Ashraful Ashem',
    gamingName: 'ASHEM_STRIKER',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    roleIds: ['role-super-admin', 'role-player'],
    playerId: 'p-ashem',
    authProvider: 'LOCAL',
    createdAt: '2025-01-01T00:00:00Z',
    lastLoginAt: '2026-09-23T10:00:00Z',
  },
  {
    id: 'usr-noyon',
    email: 'noyon@bdpsc.club',
    passwordHash: defaultHashed.hash,
    salt: defaultHashed.salt,
    name: 'Noyon Hossain',
    gamingName: 'NOYON',
    avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    roleIds: ['role-player'],
    playerId: 'p-noyon',
    authProvider: 'LOCAL',
    createdAt: '2025-06-01T00:00:00Z',
    lastLoginAt: '2026-09-22T14:30:00Z',
  },
  {
    id: 'usr-stats',
    email: 'stats@bdpsc.club',
    passwordHash: defaultHashed.hash,
    salt: defaultHashed.salt,
    name: 'Tanvir Statistics',
    gamingName: 'TANVIR_MAESTRO',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    roleIds: ['role-stats-manager', 'role-player'],
    playerId: 'p-tanvir',
    authProvider: 'LOCAL',
    createdAt: '2025-08-15T00:00:00Z',
    lastLoginAt: '2026-09-21T09:15:00Z',
  },
  {
    id: 'usr-media',
    email: 'media@bdpsc.club',
    passwordHash: defaultHashed.hash,
    salt: defaultHashed.salt,
    name: 'Fahim Media Lead',
    gamingName: 'FAHIM_SPEED',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    roleIds: ['role-media-manager', 'role-player'],
    playerId: 'p-fahim',
    authProvider: 'LOCAL',
    createdAt: '2025-10-10T00:00:00Z',
    lastLoginAt: '2026-09-20T18:00:00Z',
  },
  {
    id: 'usr-editor',
    email: 'editor@bdpsc.club',
    passwordHash: defaultHashed.hash,
    salt: defaultHashed.salt,
    name: 'Rakibul News Editor',
    gamingName: 'RAKIB_WALL',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    roleIds: ['role-editor', 'role-player'],
    playerId: 'p-rakib',
    authProvider: 'LOCAL',
    createdAt: '2025-09-01T00:00:00Z',
    lastLoginAt: '2026-09-19T11:45:00Z',
  },
  {
    id: 'usr-member',
    email: 'member@bdpsc.club',
    passwordHash: defaultHashed.hash,
    salt: defaultHashed.salt,
    name: 'Shakil Supporter',
    gamingName: 'SHAKIL_FAN',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
    status: 'ACTIVE',
    roleIds: ['role-member'],
    authProvider: 'LOCAL',
    createdAt: '2026-01-10T00:00:00Z',
    lastLoginAt: '2026-09-18T16:20:00Z',
  },
];

export const initialAnnouncements: ClubAnnouncement[] = [
  {
    id: 'ann-1',
    title: 'NATIONAL CHAMPIONS 2026',
    content: 'BD Power Strikers crowned Bangladesh National eFootball Champions 2026! Dominant grand final victory secured.',
    type: 'CELEBRATION',
    isActive: true,
    priority: 100,
    actionLink: 'trophies',
    actionLabel: 'View Trophy Showcase',
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'ann-2',
    title: 'NEXT MATCHDAY',
    content: 'BD Power Strikers vs Dhaka Titans • Championship Series Matchday 15 scheduled for this Sunday at 8:00 PM BST.',
    type: 'MATCH',
    isActive: true,
    priority: 90,
    actionLink: 'matches',
    actionLabel: 'Match Fixture Details',
    createdAt: '2026-09-22T14:30:00Z',
    updatedAt: '2026-09-22T14:30:00Z',
  },
  {
    id: 'ann-3',
    title: 'OFFICIAL SQUAD ROSTER',
    content: 'Starting XI finalized for upcoming Asian eFootball Qualifiers. Dynamic player rating formula v2.4 now live across all leaderboards.',
    type: 'ROSTER',
    isActive: true,
    priority: 80,
    actionLink: 'players',
    actionLabel: 'Explore Squad Profiles',
    createdAt: '2026-09-24T08:00:00Z',
    updatedAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'ann-4',
    title: 'ACADEMY TRIALS OPEN',
    content: 'Season 2 Scouting Trials & Open Recruitment is now active. High-ranking competitive mobile & console athletes can submit trial logs.',
    type: 'TOURNAMENT',
    isActive: true,
    priority: 70,
    actionLink: 'news',
    actionLabel: 'Read Press Release',
    createdAt: '2026-09-25T11:00:00Z',
    updatedAt: '2026-09-25T11:00:00Z',
  },
  {
    id: 'ann-5',
    title: 'DYNAMIC ELO LEADERBOARD',
    content: 'Automated performance scoring updated: Win rate, clean sheets, and MOTM stats now recalculating live.',
    type: 'UPDATE',
    isActive: true,
    priority: 60,
    actionLink: 'rankings',
    actionLabel: 'Check Rankings',
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: '2026-09-26T09:00:00Z',
  },
];



